cidr_name         = "10.0.0.0/16"
vpc_tag_name      = "Dev Vpc"
aws_profile       = "dev"
dns_name          = "dev.trishaghorpade16.me"
aws_region        = "us-east-1"
aws_subnet_count  = 3
my_ip             = "155.33.135.18/32"
my_ami            = "ami-01577ae853f199a8a"
db_storage_size   = 20
db_instance_class = "db.t3.micro"
db_engine         = "mysql"
db_engine_version = "5.7"
db_name           = "sonoo"
db_username       = "root"
db_password       = "password"
db_public_access  = false
db_multiaz        = false
zone_id           = "Z04206273AIGJGY3GTKBW"