cidr_name         = "10.0.0.0/16"
vpc_tag_name      = "Dev Vpc"
aws_profile       = "dev"
domain_name       = "dev.trishaghorpade16.me"
aws_region        = "us-east-1"
aws_subnet_count  = 3
my_ip             = "155.33.133.39/32"
my_ami            = "ami-0bd8a5cd88d8e62cd"
db_storage_size   = 20
db_instance_class = "db.t3.micro"
db_engine         = "mysql"
db_engine_version = "5.7"
db_name           = "sonoo"
db_username       = "root"
db_password       = "password"
db_public_access  = false
db_multiaz        = false
zone_id           = "Z04206273AIGJGY3GTKBW"