cidr_name        = "10.0.0.0/16"
vpc_tag_name     = "Dev Vpc"
aws_profile      = "dev"
aws_region       = "us-east-1"
aws_subnet_count = 3
my_ip            = "73.249.105.202/32"
my_ami           = "ami-0e85a54cb24708b16"
db_storage_size   = 20
db_instance_class = "db.t3.micro"
db_engine         = "mysql"
db_engine_version = "5.7"
db_name           = "sonoo"
db_username       = "root"
db_password       = "password"
db_public_access  = false
db_multiaz        = false
